CREATE ROLE IF NOT EXISTS AIRBYTE_RAW_LOADER;

CREATE WAREHOUSE IF NOT EXISTS NORTHSTYLE_ELT_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NORTHSTYLE_RAW;

CREATE SCHEMA IF NOT EXISTS NORTHSTYLE_RAW.RAW;
CREATE SCHEMA IF NOT EXISTS NORTHSTYLE_RAW.AIRBYTE_INTERNAL;

GRANT USAGE ON WAREHOUSE NORTHSTYLE_ELT_WH TO ROLE AIRBYTE_RAW_LOADER;
GRANT USAGE ON DATABASE NORTHSTYLE_RAW TO ROLE AIRBYTE_RAW_LOADER;

GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA NORTHSTYLE_RAW.RAW
  TO ROLE AIRBYTE_RAW_LOADER;

GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA NORTHSTYLE_RAW.AIRBYTE_INTERNAL
  TO ROLE AIRBYTE_RAW_LOADER;

