CREATE USER IF NOT EXISTS AIRBYTE_NORTHSTYLE
  PASSWORD = '<CHANGE_ME>'
  DEFAULT_ROLE = AIRBYTE_RAW_LOADER
  DEFAULT_WAREHOUSE = NORTHSTYLE_ELT_WH
  DEFAULT_NAMESPACE = NORTHSTYLE_RAW.RAW
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE AIRBYTE_RAW_LOADER TO USER AIRBYTE_NORTHSTYLE;

