CREATE USER IF NOT EXISTS AIRBYTE_NORTHSTYLE
  DEFAULT_ROLE = AIRBYTE_RAW_LOADER
  DEFAULT_WAREHOUSE = NORTHSTYLE_ELT_WH
  DEFAULT_NAMESPACE = NORTHSTYLE_RAW.RAW
  RSA_PUBLIC_KEY = '<PASTE_RSA_PUBLIC_KEY_HERE>';

GRANT ROLE AIRBYTE_RAW_LOADER TO USER AIRBYTE_NORTHSTYLE;

